### PR TITLE
communication after discovery

### PR DESCRIPTION
**Pull request by ruthbrennankk**

### CODE REVIEW

**Review by amphineko — CHANGES_REQUESTED** [review]
Don't couple the discovery and the upper transport protocol.

Discovery is only for announcing the listening port of the local transport protocol server.

**Comment by amphineko** [comment]
Basically, the workflow would be that the daemon runs both the discovery module and the transport module.

While the discovery module reports any received announcement from other nodes, the daemon thread will read the discovered remote endpoint and add it to the transport module.

**Comment by ruthbrennankk** [comment]
Thank you, that makes sense
I've updated Transport to be a separate class and just changed Daemon to reflect that, let me know if that's okay or if I should change anything else :)

**Review by amphineko — CHANGES_REQUESTED** [review]
Would you reuse the transport socket in the transport module?

**Pull request merged**
